---

require: rubocop-minitest

AllCops:
  NewCops: enable

Naming/MethodParameterName:
  AllowedNames:
    - as

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false
