---

require: rubocop-minitest

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false
